server:
  port: 9000

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:napptilusdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
loggin:
  level: DEBUG
# Swagger-ui custom path
springdoc:
  swagger-ui:
    path: /prices/swagger-ui.html